import { existsSync, readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { env } from "../config/env.js";

export interface DeploymentArtifact {
  readonly chainId: number;
  readonly contractName: string;
  readonly contractAddress: string;
  readonly exportedAt: string;
}

function resolveDeploymentArtifactPath(): string {
  const candidates = [
    fileURLToPath(new URL("./generated/task-history.deployment.json", import.meta.url)),
    fileURLToPath(new URL("../blockchain/generated/task-history.deployment.json", import.meta.url)),
    fileURLToPath(new URL("../../src/blockchain/generated/task-history.deployment.json", import.meta.url)),
  ];

  for (const candidate of candidates) {
    if (existsSync(candidate)) {
      return candidate;
    }
  }

  throw new Error(
    `TaskHistory deployment artifact not found in candidate paths: ${candidates.join(", ")}`,
  );
}

/**
 * BC-17: Dynamically loads the contract address from the deployment artifact
 * generated by the contract project, rather than hardcoding addresses in code.
 */
export function getDeploymentArtifact(): DeploymentArtifact {
  try {
    const artifactPath = resolveDeploymentArtifactPath();
    const content = JSON.parse(readFileSync(artifactPath, "utf8")) as DeploymentArtifact;
    return content;
  } catch {
    return {
      chainId: env.CHAIN_ID,
      contractName: "TaskHistory",
      contractAddress: env.TASK_HISTORY_CONTRACT_ADDRESS,
      exportedAt: new Date().toISOString(),
    };
  }
}

export function getVerifiedContractAddress(): `0x${string}` {
  const artifact = getDeploymentArtifact();
  // Environment override takes precedence if explicitly passed
  const address = env.TASK_HISTORY_CONTRACT_ADDRESS || artifact.contractAddress;
  return address.toLowerCase() as `0x${string}`;
}
